### PR TITLE
* Fix error. attribute can be an object or other.

### PR DESCRIPTION
**Pull request by macklus**
Hi:
I try to use your behaviour to serialice objects, but you force attribute to be a array.
This PR fix this.

Thanks in advance

### CODE REVIEW

**Comment by baibaratsky** [comment]
Sorry, your PR breaks down existing behavior. Empty array shouldn‘t be serialized. Please fix it.

**Comment by macklus** [comment]
empty arrays, also, can be serialized without problem:

if you try:
```
$value = [];
$result = serialize ($value);
```
result is: a:0:{}

**Comment by baibaratsky** [comment]
For sure. But there’s an issue. Current behavior is not to serialize them, but to put NULL value instead. And what you offer is to break the back compatibility, which is not acceptable.

**Comment by macklus** [comment]
i check about the back compatibility later.
right now, i need this working assap, so i work on my own copy.

thanks in advance

**Pull request closed without merging**
